text = {
"Credits",
"",
"Author : Anton Roy",
"",
"Apache License Version 2.0",
"",
"The Game was made with the Love2D Game Engine (love2D.org)",
"With the help of the HUMP library by Matthias Richter",
"",
"",
"",
"Story:",
"",
"In a world of balls you lived peacfully.",
"that was until the day the mysterious floating box arrived.",
"You shall become my servant or fear my fearsome power.",
"",
"As you are not wishing to bow before anything",
"not bound by the law of gravity,",
"",
"you grab your invisible sword",
"your jumping boots",
"Prepare for an epic Battle!",
"",
"",
"",
"",
"",
"Press Space to go back",
}