text = {
"Credits",
"",
"Author : Anton Roy",
"",
"Apache License Version 2.0",
"",
"The Game was made with the Love2D Game Engine (love2D.org)",
"With the help of the HUMP library by Matthias Richter",
"",
"",
"",
"Story:",
"",
"In a world of balls, you lived peacefully.",
"That was until the day a mysterious floating box appeared.",
"\"You shall become my servant or fear my fearsome power\"",
"",
"",
"You won't bow before anything...",
"...not even the law of gravity !",
"Grab your invisible sword...",
"... your jumping boots ...",
"... and prepare for an epic battle !",
"",
"",
"",
"",
"Press Space to go back",
}