text = {
	"You Won !",
	"I, the consious rectangle, shall retreat.",
	"For centuries, I will be watching you from afar.",
	"But... when your recollection of me will be nothing",
	"but a distant memory...",
	"...",
	"I",
	"will",
	"RETURN !",
	"",
	"",
	"",
	"",
	"Thanks for playing !",
	"Anton",
}